apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.incubator.k8s.io
  annotations:
    "helm.sh/hook": "crd-install"
    "api-approved.kubernetes.io": "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: scheduling.incubator.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                weight:
                  format: int32
                  type: integer
              type: object
          type: object
  names:
    kind: Queue
    plural: queues
  scope: Cluster

