apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.incubator.k8s.io
  annotations:
    "helm.sh/hook": "crd-install"
    "api-approved.kubernetes.io": "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: scheduling.incubator.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                minMember:
                  format: int32
                  type: integer
                queue:
                  type: string
                priorityClassName:
                  type: string
              type: object
            status:
              properties:
                succeeded:
                  format: int32
                  type: integer
                failed:
                  format: int32
                  type: integer
                running:
                  format: int32
                  type: integer
              type: object
          type: object
  names:
    kind: PodGroup
    plural: podgroups
  scope: Namespaced

